
---------------------------------------------
-- Annotations for built-in Osiris events.
-- Generated by OsirisIDEAnnotationGenerator feature.
---------------------------------------------

---@meta

--- @class Osi

--- @param Character Guid
function Osi.CharacterDied(Character) end

--- @param Character Guid
function Osi.CharacterResurrected(Character) end

--- @param Character Guid
function Osi.CharacterPrecogDying(Character) end

--- @param Character Guid
function Osi.CharacterDying(Character) end

--- @param TemplateName string
function Osi.CharacterTemplateDied(TemplateName) end

--- @param Character Guid
--- @param Status string
--- @param Causee Guid
function Osi.CharacterStatusAttempt(Character, Status, Causee) end

--- @param Character Guid
--- @param Status string
--- @param Causee Guid
function Osi.CharacterStatusApplied(Character, Status, Causee) end

--- @param Character Guid
--- @param Status string
--- @param Causee Guid
function Osi.CharacterStatusRemoved(Character, Status, Causee) end

--- @param Character Guid
--- @param Item Guid
function Osi.CharacterUsedItem(Character, Item) end

--- @param Character Guid
--- @param Template string
--- @param Item Guid
function Osi.CharacterUsedItemTemplate(Character, Template, Item) end

--- @param Character Guid
--- @param Item Guid
function Osi.CharacterUsedItemFailed(Character, Item) end

--- @param Character Guid
function Osi.CharacterUsedLadder(Character) end

--- @param Character Guid
--- @param Item Guid
function Osi.CharacterPreMovedItem(Character, Item) end

--- @param Character Guid
--- @param Item Guid
function Osi.CharacterMovedItem(Character, Item) end

--- @param Character Guid
--- @param Template string
function Osi.CharacterMovedItemTemplate(Character, Template) end

--- @param Character Guid
--- @param Region string
function Osi.CharacterEnteredRegion(Character, Region) end

--- @param Character Guid
--- @param Region string
function Osi.CharacterLeftRegion(Character, Region) end

--- @param Character Guid
--- @param OtherCharacter Guid
function Osi.CharacterSawCharacter(Character, OtherCharacter) end

--- @param Character Guid
--- @param OtherCharacter Guid
function Osi.CharacterSawSneakingCharacter(Character, OtherCharacter) end

--- @param Character Guid
--- @param OtherCharacter Guid
function Osi.CharacterLostSightOfCharacter(Character, OtherCharacter) end

--- @param Defender Guid
--- @param AttackOwner Guid
--- @param Attacker Guid
function Osi.CharacterBlockedBy(Defender, AttackOwner, Attacker) end

--- @param Defender Guid
--- @param AttackOwner Guid
--- @param Attacker Guid
function Osi.CharacterMissedBy(Defender, AttackOwner, Attacker) end

--- @param Defender Guid
--- @param AttackOwner Guid
--- @param Attacker Guid
function Osi.CharacterPhysicalHitBy(Defender, AttackOwner, Attacker) end

--- @param Defender Guid
--- @param AttackOwner Guid
--- @param Attacker Guid
function Osi.CharacterCriticalHitBy(Defender, AttackOwner, Attacker) end

--- @param Defender Guid
--- @param AttackOwner Guid
--- @param Attacker Guid
function Osi.CharacterKilledBy(Defender, AttackOwner, Attacker) end

--- @param CharacterTemplate string
--- @param Killer Guid
function Osi.CharacterTemplateKilledByCharacter(CharacterTemplate, Killer) end

--- @param Defender Guid
--- @param AttackOwner Guid
--- @param Attacker Guid
function Osi.CharacterStartAttackObject(Defender, AttackOwner, Attacker) end

--- @param x number
--- @param y number
--- @param z number
--- @param AttackOwner Guid
--- @param Attacker Guid
function Osi.CharacterStartAttackPosition(x, y, z, AttackOwner, Attacker) end

--- @param Character Guid
--- @param OtherCharacter Guid
--- @param NewRelation integer
function Osi.CharacterChangedAlginmentToCharacter(Character, OtherCharacter, NewRelation) end

--- @param Character Guid
--- @param Trigger Guid
function Osi.CharacterEnteredTrigger(Character, Trigger) end

--- @param Character Guid
--- @param Percentage integer
--- @param Source Guid
function Osi.CharacterReceivedDamage(Character, Percentage, Source) end

--- @param Character Guid
--- @param Percentage integer
function Osi.CharacterVitalityChanged(Character, Percentage) end

--- @param Character Guid
--- @param Trigger Guid
function Osi.CharacterLeftTrigger(Character, Trigger) end

--- @param Player Guid
--- @param NPC Guid
--- @param Item Guid
--- @param Amount integer
function Osi.CharacterPickpocketSuccess(Player, NPC, Item, Amount) end

--- @param Character Guid
--- @param Player Guid
--- @param NewAttitude integer
function Osi.CharacterAttitudeTowardsPlayerChanged(Character, Player, NewAttitude) end

--- @param Player Guid
--- @param Item Guid
function Osi.ItemSendToHomesteadEvent(Player, Item) end

--- @param Character Guid
--- @param Item Guid
--- @param Event string
function Osi.CharacterItemEvent(Character, Item, Event) end

--- @param Character Guid
--- @param Skill string
--- @param SkillType string
--- @param SkillElement string
function Osi.CharacterUsedSkill(Character, Skill, SkillType, SkillElement) end

--- @param Character Guid
--- @param X number
--- @param Y number
--- @param Z number
--- @param Skill string
--- @param SkillType string
--- @param SkillElement string
function Osi.CharacterUsedSkillAtPosition(Character, X, Y, Z, Skill, SkillType, SkillElement) end

--- @param Character Guid
--- @param Target Guid
--- @param Skill string
--- @param SkillType string
--- @param SkillElement string
function Osi.CharacterUsedSkillOnTarget(Character, Target, Skill, SkillType, SkillElement) end

--- @param Character Guid
--- @param Target Guid
--- @param Skill string
--- @param SkillType string
--- @param SkillElement string
function Osi.CharacterUsedSkillOnZoneWithTarget(Character, Target, Skill, SkillType, SkillElement) end

--- @param Character Guid
--- @param Skill string
--- @param SkillType string
--- @param SkillElement string
--- @param Trigger Guid
function Osi.CharacterUsedSkillInTrigger(Character, Skill, SkillType, SkillElement, Trigger) end

--- @param Character Guid
--- @param Skill string
function Osi.CharacterLearnedSkill(Character, Skill) end

--- @param Character Guid
--- @param Skill string
--- @param SkillType string
--- @param SkillElement string
function Osi.SkillCast(Character, Skill, SkillType, SkillElement) end

--- @param Player Guid
--- @param NPC Guid
function Osi.RequestPickpocket(Player, NPC) end

--- @param Player Guid
--- @param NPC Guid
function Osi.CharacterPickpocketFailed(Player, NPC) end

--- @param Player Guid
--- @param Corpse Guid
function Osi.CharacterLootedCharacterCorpse(Player, Corpse) end

--- @param Character Guid
--- @param Trader Guid
function Osi.RequestTrade(Character, Trader) end

--- @param Character Guid
--- @param Trader Guid
--- @param CharacterValue integer
--- @param TraderValue integer
function Osi.HappyWithDeal(Character, Trader, CharacterValue, TraderValue) end

--- @param Character Guid
--- @param Trader Guid
function Osi.TradeEnds(Character, Trader) end

--- @param Character Guid
--- @param FrameID string
function Osi.CharacterScriptFrameFinished(Character, FrameID) end

--- @param Character1 Guid
--- @param Character2 Guid
--- @param Event string
function Osi.CharacterCharacterEvent(Character1, Character2, Event) end

--- @param Character Guid
--- @param OtherCharacter Guid
--- @param Attitude integer
function Osi.CharacterRelationChangedTo(Character, OtherCharacter, Attitude) end

--- @param Character Guid
--- @param Item Guid
function Osi.CharacterDestroyedItem(Character, Item) end

--- @param Character Guid
--- @param ItemTemplate string
function Osi.CharacterDestroyedItemTemplate(Character, ItemTemplate) end

--- @param Character Guid
--- @param DisplayText string
function Osi.CharacterDisplayTextEnded(Character, DisplayText) end

--- @param Character1 Guid
--- @param Character2 Guid
function Osi.CharacterSetTemporaryRelationsFailed(Character1, Character2) end

--- @param Character Guid
function Osi.CharacterMadePlayer(Character) end

--- @param Character Guid
function Osi.CharacterLeveledUp(Character) end

--- @param Character Guid
--- @param Talent string
function Osi.CharacterUnlockedTalent(Character, Talent) end

--- @param Character Guid
--- @param Talent string
function Osi.CharacterLockedTalent(Character, Talent) end

--- @param Character Guid
--- @param Ability string
--- @param OldBaseValue integer
--- @param NewBaseValue integer
function Osi.CharacterBaseAbilityChanged(Character, Ability, OldBaseValue, NewBaseValue) end

--- @param Character Guid
--- @param Message string
function Osi.MessageBoxClosed(Character, Message) end

--- @param Character Guid
--- @param Message string
--- @param Result integer
function Osi.MessageBoxYesNoClosed(Character, Message, Result) end

--- @param Character Guid
--- @param Message string
--- @param ResultChoice string
function Osi.MessageBoxChoiceClosed(Character, Message, ResultChoice) end

--- @param Character Guid
--- @param Message string
function Osi.TutorialBoxClosed(Character, Message) end

--- @param Character Guid
--- @param Trait string
function Osi.CharacterTraitChanged(Character, Trait) end

--- @param Character Guid
function Osi.CharacterGuarded(Character) end

--- @param Character Guid
--- @param Bool integer
function Osi.CharacterWentOnStage(Character, Bool) end

--- @param Character Guid
--- @param OldUserID integer
--- @param NewUserID integer
function Osi.CharacterReservedUserIDChanged(Character, OldUserID, NewUserID) end

--- @param Character Guid
function Osi.CharacterAddedToGroup(Character) end

--- @param Character Guid
function Osi.CharacterDetachedFromGroup(Character) end

--- @param Character Guid
--- @param Item Guid
function Osi.CharacterStartLockpickingItem(Character, Item) end

--- @param Character Guid
--- @param Item Guid
function Osi.CharacterStoppedLockpickingItem(Character, Item) end

--- @param Character Guid
--- @param Item Guid
function Osi.CharacterStoppedUsingItem(Character, Item) end

--- @param Character Guid
--- @param ItemA Guid
--- @param ItemB Guid
--- @param ItemC Guid
--- @param ItemD Guid
--- @param ItemE Guid
function Osi.CharacterStoppedCombiningItems(Character, ItemA, ItemB, ItemC, ItemD, ItemE) end

--- @param Character Guid
--- @param Ghost Guid
function Osi.CharacterTurnedToGhost(Character, Ghost) end

--- @param Character Guid
--- @param Ghost Guid
function Osi.CharacterGhostDestroyed(Character, Ghost) end

--- @param Character Guid
--- @param Ghost Guid
function Osi.CharacterGhostRevealed(Character, Ghost) end

--- @param Character Guid
--- @param CrimeRegion string
--- @param CrimeID integer
--- @param PriortiyName string
--- @param PrimaryDialog string
--- @param Criminal1 Guid
--- @param Criminal2 Guid
--- @param Criminal3 Guid
--- @param Criminal4 Guid
--- @param IsPrimary integer
function Osi.CharacterOnCrimeSensibleActionNotification(Character, CrimeRegion, CrimeID, PriortiyName, PrimaryDialog, Criminal1, Criminal2, Criminal3, Criminal4, IsPrimary) end

--- @param Character Guid
--- @param CrimeRegion string
--- @param UnavailableForCrimeID integer
--- @param BusyCrimeID integer
--- @param Criminal1 Guid
--- @param Criminal2 Guid
--- @param Criminal3 Guid
--- @param Criminal4 Guid
function Osi.CharacterSelectedAsBestUnavailableFallbackLead(Character, CrimeRegion, UnavailableForCrimeID, BusyCrimeID, Criminal1, Criminal2, Criminal3, Criminal4) end

--- @param Victim Guid
--- @param CrimeType string
--- @param CrimeID integer
--- @param Evidence Guid
--- @param Criminal1 Guid
--- @param Criminal2 Guid
--- @param Criminal3 Guid
--- @param Criminal4 Guid
function Osi.CrimeIsRegistered(Victim, CrimeType, CrimeID, Evidence, Criminal1, Criminal2, Criminal3, Criminal4) end

--- @param Character Guid
--- @param UserID integer
function Osi.CharacterSelectedInCharCreation(Character, UserID) end

--- @param Character Guid
--- @param UserID integer
--- @param Origin string
function Osi.CharacterStartOriginIntroduction(Character, UserID, Origin) end

--- @param Character Guid
--- @param UserID integer
function Osi.CharacterStopOriginIntroduction(Character, UserID) end

--- @param Character Guid
--- @param Team integer
function Osi.CharacterCreatedInArena(Character, Team) end

--- @param Character Guid
function Osi.CharacterUsedSourcePoint(Character) end

--- @param Character Guid
--- @param Skill string
--- @param Learned integer
function Osi.SkillAdded(Character, Skill, Learned) end

--- @param Character Guid
--- @param Skill string
function Osi.SkillActivated(Character, Skill) end

--- @param Character Guid
--- @param Skill string
function Osi.SkillDeactivated(Character, Skill) end

--- @param Target Guid
--- @param Cause Guid
--- @param OldX number
--- @param OldY number
--- @param OldZ number
--- @param NewX number
--- @param NewY number
--- @param NewZ number
--- @param Skill string
function Osi.CharacterTeleported(Target, Cause, OldX, OldY, OldZ, NewX, NewY, NewZ, Skill) end

--- @param Character Guid
--- @param Target Guid
--- @param MoveID string
function Osi.CharacterMoveToAndTalkFailed(Character, Target, MoveID) end

--- @param Character Guid
--- @param Target Guid
--- @param DialogID string
--- @param IsAutomated integer
--- @param MoveID string
function Osi.CharacterMoveToAndTalkRequestDialog(Character, Target, DialogID, IsAutomated, MoveID) end

--- @param Character Guid
--- @param Target Guid
--- @param MoveId string
function Osi.CharacterMoveToAndTalkRequestDialogFailedEvent(Character, Target, MoveId) end

--- @param Character Guid
function Osi.CharacterJoinedParty(Character) end

--- @param Character Guid
function Osi.CharacterLeftParty(Character) end

--- @param Character Guid
function Osi.CharacterLoadedInPreset(Character) end

--- @param Character Guid
--- @param Race string
function Osi.CharacterPolymorphedInto(Character, Race) end

--- @param Character Guid
function Osi.CharacterStoppedPolymorph(Character) end

--- @param Character Guid
--- @param Pyramid Guid
function Osi.CharacterTeleportToPyramid(Character, Pyramid) end

--- @param Character Guid
--- @param Trigger Guid
function Osi.CharacterTeleportToWaypoint(Character, Trigger) end

--- @param Character Guid
--- @param Trigger Guid
function Osi.CharacterTeleportToFleeWaypoint(Character, Trigger) end

--- @param Character Guid
--- @param Item Guid
--- @param Trigger Guid
function Osi.CharacterTeleportByItem(Character, Item, Trigger) end

--- @param Character Guid
--- @param Item Guid
--- @param X number
--- @param Y number
--- @param Z number
--- @param OldOwner Guid
--- @param SrcContainer Guid
--- @param Amount integer
function Osi.CharacterStoleItem(Character, Item, X, Y, Z, OldOwner, SrcContainer, Amount) end

--- @param Character Guid
function Osi.CharacterRequestsHomestead(Character) end

--- @param Character Guid
--- @param Recipe string
function Osi.CharacterUnlockedRecipe(Character, Recipe) end

--- @param Character Guid
--- @param Target Guid
function Osi.CharacterPickpocketEnter(Character, Target) end

--- @param Character Guid
function Osi.CharacterPickpocketExit(Character) end

--- @param Item Guid
--- @param Character Guid
function Osi.ItemAddedToCharacter(Item, Character) end

--- @param Item Guid
function Osi.ItemOpened(Item) end

--- @param ItemTemplate string
--- @param Item Guid
--- @param Character Guid
function Osi.ItemTemplateOpening(ItemTemplate, Item, Character) end

--- @param Item Guid
function Osi.ItemDestroying(Item) end

--- @param Item Guid
function Osi.ItemDestroyed(Item) end

--- @param TemplateID string
--- @param Item Guid
function Osi.ItemTemplateDestroyed(TemplateID, Item) end

--- @param Trigger Guid
--- @param TemplateID string
--- @param Item Guid
function Osi.ItemCreatedAtTrigger(Trigger, TemplateID, Item) end

--- @param Item Guid
function Osi.ItemClosed(Item) end

--- @param Item Guid
function Osi.ItemDropped(Item) end

--- @param Item Guid
--- @param Trigger Guid
--- @param Mover Guid
function Osi.ItemEnteredTrigger(Item, Trigger, Mover) end

--- @param ItemTemplate string
--- @param Item Guid
--- @param Trigger Guid
--- @param Owner Guid
--- @param Mover Guid
function Osi.ItemTemplateEnteredTrigger(ItemTemplate, Item, Trigger, Owner, Mover) end

--- @param Item Guid
--- @param Trigger Guid
--- @param Mover Guid
function Osi.ItemLeftTrigger(Item, Trigger, Mover) end

--- @param ItemTemplate string
--- @param Item Guid
--- @param Trigger Guid
--- @param Owner Guid
--- @param Mover Guid
function Osi.ItemTemplateLeftTrigger(ItemTemplate, Item, Trigger, Owner, Mover) end

--- @param Item Guid
--- @param Container Guid
function Osi.ItemAddedToContainer(Item, Container) end

--- @param ItemTemplate Guid
--- @param Item Guid
--- @param Character Guid
function Osi.ItemTemplateAddedToCharacter(ItemTemplate, Item, Character) end

--- @param ItemTemplate string
--- @param Item Guid
--- @param Container Guid
function Osi.ItemTemplateAddedToContainer(ItemTemplate, Item, Container) end

--- @param Item Guid
--- @param Character Guid
function Osi.ItemRemovedFromCharacter(Item, Character) end

--- @param ItemTemplate string
--- @param Item Guid
--- @param Character Guid
function Osi.ItemTemplateRemovedFromCharacter(ItemTemplate, Item, Character) end

--- @param Item Guid
--- @param Container Guid
function Osi.ItemRemovedFromContainer(Item, Container) end

--- @param ItemTemplate string
--- @param Item Guid
--- @param Container Guid
function Osi.ItemTemplateRemovedFromContainer(ItemTemplate, Item, Container) end

--- @param Item Guid
--- @param Character Guid
function Osi.ItemEquipped(Item, Character) end

--- @param Item Guid
--- @param Character Guid
function Osi.ItemUnEquipped(Item, Character) end

--- @param ItemTemplate string
--- @param Character Guid
function Osi.ItemTemplateEquipped(ItemTemplate, Character) end

--- @param ItemTemplate string
--- @param Character Guid
function Osi.ItemTemplateUnEquipped(ItemTemplate, Character) end

--- @param ItemSetName string
--- @param Character Guid
function Osi.ItemSetEquipped(ItemSetName, Character) end

--- @param ItemSetName string
--- @param Character Guid
function Osi.ItemSetUnEquipped(ItemSetName, Character) end

--- @param Item Guid
function Osi.ItemMoved(Item) end

--- @param ItemTemplate string
--- @param Item Guid
function Osi.ItemTemplateMoved(ItemTemplate, Item) end

--- @param Item Guid
--- @param DisplayText string
function Osi.ItemDisplayTextEnded(Item, DisplayText) end

--- @param FirstItemTemplate string
--- @param SecondItemTemplate string
--- @param ThirdItemTemplate string
--- @param ForthItemTemplate string
--- @param FifthItemTemplate string
--- @param Character Guid
--- @param NewItem Guid
function Osi.ItemTemplateCombinedWithItemTemplate(FirstItemTemplate, SecondItemTemplate, ThirdItemTemplate, ForthItemTemplate, FifthItemTemplate, Character, NewItem) end

--- @param Item Guid
--- @param Status string
--- @param Causee Guid
function Osi.ItemStatusAttempt(Item, Status, Causee) end

--- @param Item Guid
--- @param Status string
--- @param Causee Guid
function Osi.ItemStatusChange(Item, Status, Causee) end

--- @param Item Guid
--- @param Status string
--- @param Causee Guid
function Osi.ItemStatusRemoved(Item, Status, Causee) end

--- @param Item Guid
--- @param StackedWithItem Guid
function Osi.ItemStackedWith(Item, StackedWithItem) end

--- @param Item Guid
--- @param FromObject Guid
--- @param ToObject Guid
--- @param IsTrade integer
function Osi.ItemMovedFromTo(Item, FromObject, ToObject, IsTrade) end

--- @param X number
--- @param Y number
--- @param Z number
function Osi.ItemsScatteredAt(X, Y, Z) end

--- @param Trader Guid
function Osi.TradeGenerationStarted(Trader) end

--- @param Trader Guid
function Osi.TradeGenerationEnded(Trader) end

--- @param Item Guid
--- @param Character Guid
--- @param Key Guid
function Osi.ItemUnlocked(Item, Character, Key) end

--- @param Item Guid
--- @param Character Guid
function Osi.ItemUnEquipFailed(Item, Character) end

--- @param Item Guid
function Osi.ItemReceivedDamage(Item) end

--- @param Item Guid
--- @param Bool integer
function Osi.ItemWentOnStage(Item, Bool) end

--- @param Item Guid
function Osi.ItemGhostRevealed(Item) end

--- @param Item Guid
--- @param Region string
function Osi.ItemEnteredRegion(Item, Region) end

--- @param Item Guid
--- @param Region string
function Osi.ItemLeftRegion(Item, Region) end

--- @param Character Guid
--- @param Item Guid
--- @param RuneItemTemplate string
--- @param Slot integer
function Osi.RuneInserted(Character, Item, RuneItemTemplate, Slot) end

--- @param Character Guid
--- @param Item Guid
--- @param Rune Guid
--- @param Slot integer
function Osi.RuneRemoved(Character, Item, Rune, Slot) end

--- @param Dialog string
--- @param InstanceID integer
function Osi.DialogStarted(Dialog, InstanceID) end

--- @param Dialog string
--- @param InstanceID integer
function Osi.AutomatedDialogStarted(Dialog, InstanceID) end

--- @param Dialog string
--- @param InstanceID integer
function Osi.DualDialogStart(Dialog, InstanceID) end

--- @param Dialog string
--- @param InstanceID integer
function Osi.AutomatedDialogEnded(Dialog, InstanceID) end

--- @param Dialog string
--- @param InstanceID integer
function Osi.DialogEnded(Dialog, InstanceID) end

--- @param Dialog string
--- @param InstanceID integer
function Osi.DialogRequestFailed(Dialog, InstanceID) end

--- @param Dialog string
--- @param InstanceID integer
--- @param Actor Guid
function Osi.DialogActorJoined(Dialog, InstanceID, Actor) end

--- @param Dialog string
--- @param InstanceID integer
--- @param Actor Guid
function Osi.DialogActorLeft(Dialog, InstanceID, Actor) end

--- @param Dialog string
--- @param InstanceID integer
function Osi.AutomatedDialogRequestFailed(Dialog, InstanceID) end

--- @param Target Guid
--- @param Player Guid
function Osi.DialogStartRequested(Target, Player) end

--- @param FlagName string
function Osi.GlobalFlagSet(FlagName) end

--- @param FlagName string
function Osi.GlobalFlagCleared(FlagName) end

--- @param FlagName string
--- @param Speaker Guid
--- @param DialogInstance integer
function Osi.ObjectFlagSet(FlagName, Speaker, DialogInstance) end

--- @param FlagName string
--- @param Speaker Guid
--- @param NewValue integer
function Osi.ObjectFlagShared(FlagName, Speaker, NewValue) end

--- @param FlagName string
--- @param Speaker Guid
--- @param DialogInstance integer
function Osi.ObjectFlagCleared(FlagName, Speaker, DialogInstance) end

--- @param Character Guid
--- @param Success integer
--- @param Dialog string
function Osi.PersuasionResult(Character, Success, Dialog) end

--- @param Timer string
function Osi.TimerFinished(Timer) end

--- @param NewRegion string
function Osi.RegionStarted(NewRegion) end

--- @param LevelName string
--- @param IsEditorMode integer
function Osi.GameStarted(LevelName, IsEditorMode) end

--- @param Region string
function Osi.RegionEnded(Region) end

--- @param DLCName string
--- @param UserID integer
--- @param Installed integer
function Osi.DLCUpdated(DLCName, UserID, Installed) end

--- @param Level string
function Osi.CharacterCreationStarted(Level) end

--- @param Character Guid
function Osi.CharacterCreationFinished(Character) end

--- @param Item Guid
--- @param Character Guid
function Osi.GameBookInterfaceClosed(Item, Character) end

--- @param Major integer
--- @param Minor integer
--- @param Revision integer
--- @param Build integer
function Osi.SavegameLoading(Major, Minor, Revision, Build) end

--- @param Major integer
--- @param Minor integer
--- @param Revision integer
--- @param Build integer
function Osi.SavegameLoaded(Major, Minor, Revision, Build) end

--- @param MovieName string
function Osi.MovieFinished(MovieName) end

--- @param MovieName string
function Osi.MoviePlaylistFinished(MovieName) end

--- @param DifficultyLevel integer
function Osi.DifficultyChanged(DifficultyLevel) end

--- @param GameMode string
--- @param IsEditorMode integer
function Osi.GameModeStarted(GameMode, IsEditorMode) end

--- @param Object Guid
--- @param Event string
function Osi.StoryEvent(Object, Event) end

--- @param Character Guid
--- @param Item Guid
--- @param RequestID integer
function Osi.CanMoveItem(Character, Item, RequestID) end

--- @param Character Guid
--- @param Item Guid
--- @param RequestID integer
function Osi.CanPickupItem(Character, Item, RequestID) end

--- @param Character Guid
--- @param Item Guid
--- @param RequestID integer
function Osi.CanUseItem(Character, Item, RequestID) end

--- @param Character Guid
--- @param Item Guid
--- @param RequestID integer
function Osi.CanLockpickItem(Character, Item, RequestID) end

--- @param Character Guid
--- @param ItemA Guid
--- @param ItemB Guid
--- @param ItemC Guid
--- @param ItemD Guid
--- @param ItemE Guid
--- @param RequestID integer
function Osi.CanCombineItem(Character, ItemA, ItemB, ItemC, ItemD, ItemE, RequestID) end

--- @param UserID integer
--- @param UserName string
--- @param UserProfileID string
function Osi.UserConnected(UserID, UserName, UserProfileID) end

--- @param UserID integer
--- @param FadeID string
function Osi.FadeOutDone(UserID, FadeID) end

--- @param UserID integer
--- @param FadeID string
function Osi.FadeInDone(UserID, FadeID) end

--- @param UserID integer
--- @param FadeID string
function Osi.FadeDone(UserID, FadeID) end

--- @param UserID integer
--- @param FadeID string
function Osi.ClearFadeDone(UserID, FadeID) end

--- @param UserID integer
--- @param UserName string
--- @param UserProfileID string
function Osi.UserDisconnected(UserID, UserName, UserProfileID) end

--- @param UserID integer
--- @param UserEvent string
function Osi.UserEvent(UserID, UserEvent) end

--- @param SourceUserID integer
--- @param TargetUserID integer
--- @param War integer
function Osi.UserMakeWar(SourceUserID, TargetUserID, War) end

--- @param Defender Guid
--- @param AttackerOwner Guid
--- @param Attacker Guid
--- @param DamageType string
--- @param DamageSource string
function Osi.AttackedByObject(Defender, AttackerOwner, Attacker, DamageType, DamageSource) end

--- @param Character Guid
function Osi.FleeCombat(Character) end

--- @param CrimeRegion string
--- @param CrimeID integer
--- @param Interrogator Guid
--- @param Criminal1 Guid
--- @param Criminal2 Guid
--- @param Criminal3 Guid
--- @param Criminal4 Guid
--- @param InterrogateDialog string
function Osi.CrimeInterrogationRequest(CrimeRegion, CrimeID, Interrogator, Criminal1, Criminal2, Criminal3, Criminal4, InterrogateDialog) end

--- @param CrimeID integer
--- @param Victim Guid
--- @param Criminal1 Guid
--- @param Criminal2 Guid
--- @param Criminal3 Guid
--- @param Criminal4 Guid
function Osi.OnCrimeResolved(CrimeID, Victim, Criminal1, Criminal2, Criminal3, Criminal4) end

--- @param CrimeID integer
--- @param Victim Guid
--- @param Criminal1 Guid
--- @param Criminal2 Guid
--- @param Criminal3 Guid
--- @param Criminal4 Guid
function Osi.OnCrimeRemoved(CrimeID, Victim, Criminal1, Criminal2, Criminal3, Criminal4) end

--- @param CrimeID integer
--- @param Investigator Guid
--- @param WasLead integer
--- @param Criminal1 Guid
--- @param Criminal2 Guid
--- @param Criminal3 Guid
--- @param Criminal4 Guid
function Osi.OnCrimeConfrontationDone(CrimeID, Investigator, WasLead, Criminal1, Criminal2, Criminal3, Criminal4) end

--- @param CrimeID integer
--- @param Criminal Guid
function Osi.OnCriminalMergedWithCrime(CrimeID, Criminal) end

--- @param OldCrimeID integer
--- @param NewCrimeID integer
function Osi.OnCrimeMergedWith(OldCrimeID, NewCrimeID) end

--- @param CrimeID integer
--- @param Character Guid
--- @param Criminal1 Guid
function Osi.OnCrimeSawCriminalInCombat(CrimeID, Character, Criminal1) end

--- @param Mutator string
--- @param Turn integer
function Osi.OnMutatorEnabledAtTurn(Mutator, Turn) end

--- @param ArenaMode string
function Osi.OnArenaRoundStarted(ArenaMode) end

--- @param Object Guid
--- @param Bool integer
function Osi.OnStageChanged(Object, Bool) end

--- @param Object Guid
--- @param Tag string
function Osi.ObjectWasTagged(Object, Tag) end

--- @param Object Guid
--- @param Tag string
function Osi.ObjectLostTag(Object, Tag) end

--- @param Object Guid
--- @param CombatID integer
function Osi.ObjectEnteredCombat(Object, CombatID) end

--- @param CombatID integer
function Osi.CombatStarted(CombatID) end

--- @param CombatID integer
--- @param Round integer
function Osi.CombatRoundStarted(CombatID, Round) end

--- @param CombatID integer
function Osi.CombatEnded(CombatID) end

--- @param Object Guid
--- @param OldCombatID integer
--- @param NewCombatID integer
function Osi.ObjectSwitchedCombat(Object, OldCombatID, NewCombatID) end

--- @param Object Guid
--- @param CombatID integer
function Osi.ObjectLeftCombat(Object, CombatID) end

--- @param Object Guid
--- @param CombatID integer
function Osi.ObjectReadyInCombat(Object, CombatID) end

--- @param Object Guid
function Osi.ObjectTurnStarted(Object) end

--- @param Object Guid
function Osi.ObjectTurnEnded(Object) end

--- @param Object Guid
--- @param ToTemplate Guid
function Osi.ObjectTransformed(Object, ToTemplate) end

--- @param Character Guid
--- @param Crime string
function Osi.CrimeDisabled(Character, Crime) end

--- @param Character Guid
--- @param Crime string
function Osi.CrimeEnabled(Character, Crime) end

--- @param CampaignMode string
function Osi.GMCampaignModeStarted(CampaignMode) end

--- @param PartyPreset string
function Osi.PartyPresetLoaded(PartyPreset) end

--- @param Character Guid
--- @param Quest string
--- @param IsShared integer
function Osi.QuestShared(Character, Quest, IsShared) end

--- @param Quest string
--- @param NewCategory string
function Osi.QuestCategoryChanged(Quest, NewCategory) end

--- @param Character Guid
--- @param MysteryID string
function Osi.MysteryUnlocked(Character, MysteryID) end

--- @param Id string
function Osi.ReadyCheckPassed(Id) end

--- @param Id string
function Osi.ReadyCheckFailed(Id) end

--- @param Target Guid
--- @param AddSP integer
--- @param WasSP integer
function Osi.ObjectSourcePointAddRequest(Target, AddSP, WasSP) end

--- @param UserId integer
--- @param EventId string
function Osi.TeleportRequestMovie(UserId, EventId) end

--- @param UserId integer
--- @param EventId string
function Osi.EndGameRequestMovie(UserId, EventId) end

--- @param Character Guid
--- @param BookName string
function Osi.CustomBookUIClosed(Character, BookName) end

--- @param Character Guid
--- @param UIInstance string
--- @param Type integer
--- @param Command string
--- @param ElementId integer
function Osi.PuzzleUIUsed(Character, UIInstance, Type, Command, ElementId) end

--- @param Character Guid
--- @param UIInstance string
--- @param Type integer
function Osi.PuzzleUIClosed(Character, UIInstance, Type) end

--- @param Spline Guid
--- @param Character Guid
--- @param event string
--- @param index integer
--- @param last integer
function Osi.CameraReachedNode(Spline, Character, event, index, last) end

--- @param Bark string
--- @param InstanceID integer
function Osi.VoiceBarkStarted(Bark, InstanceID) end

--- @param Bark string
function Osi.VoiceBarkFailed(Bark) end

--- @param Bark string
--- @param InstanceID integer
function Osi.VoiceBarkEnded(Bark, InstanceID) end

--- @param Dialog string
--- @param InstanceID integer
--- @param TargetInstanceID integer
function Osi.DualDialogRequested(Dialog, InstanceID, TargetInstanceID) end

--- @param Dialog string
--- @param InstanceID integer
--- @param TargetInstanceID integer
function Osi.ChildDialogRequested(Dialog, InstanceID, TargetInstanceID) end

--- @param Event string
function Osi.GameEventSet(Event) end

--- @param Event string
function Osi.GameEventCleared(Event) end

--- @param Event string
function Osi.TextEventSet(Event) end

--- @param Event string
--- @param Num integer
function Osi.NRD_Loop(Event, Num) end

--- @param Object Guid
--- @param Event string
--- @param Num integer
function Osi.NRD_Loop(Object, Event, Num) end

--- @param Event string
--- @param Object Guid
--- @param StatusId string
--- @param StatusHandle integer
function Osi.NRD_StatusIteratorEvent(Event, Object, StatusId, StatusHandle) end

--- @param Target Guid
--- @param StatusId string
--- @param StatusHandle integer
--- @param Instigator Guid
function Osi.NRD_OnStatusAttempt(Target, StatusId, StatusHandle, Instigator) end

--- @param Target Guid
--- @param Instigator Guid
--- @param Damage integer
--- @param HitHandle integer
function Osi.NRD_OnPrepareHit(Target, Instigator, Damage, HitHandle) end

--- @param Target Guid
--- @param Instigator Guid
--- @param Damage integer
--- @param StatusHandle integer
function Osi.NRD_OnHit(Target, Instigator, Damage, StatusHandle) end

--- @param Target Guid
--- @param Instigator Guid
--- @param Amount integer
--- @param StatusHandle integer
function Osi.NRD_OnHeal(Target, Instigator, Amount, StatusHandle) end

--- @param Character Guid
--- @param Action string
function Osi.NRD_OnActionStateEnter(Character, Action) end

--- @param Event string
--- @param Item Guid
--- @param DeltaMod string
--- @param IsGenerated integer
function Osi.NRD_ItemDeltaModIteratorEvent(Event, Item, DeltaMod, IsGenerated) end

--- @param Event string
--- @param Character Guid
--- @param SkillId string
--- @param IsLearned integer
--- @param IsActivated integer
function Osi.NRD_SkillIteratorEvent(Event, Character, SkillId, IsLearned, IsActivated) end

--- @param Character Guid
--- @param Action string
function Osi.NRD_OnActionStateExit(Character, Action) end

