
---@class GameStateLib : Feature
GameState = {
    SERVER_STATES = {
        UNKNOWN = "Unknown",
        UNINITIALIZED = "Uninitialized",
        INIT = "Init",
        IDLE = "Idle",
        EXIT = "Exit",
        LOAD_LEVEL = "LoadLevel",
        LOAD_MODULE = "LoadModule",
        LOAD_GM_CAMPAIGN = "LoadGMCampaign",
        LOAD_SESSION = "LoadSession",
        UNLOAD_LEVEL = "UnloadLevel",
        UNLOAD_MODULE = "UnloadModule",
        UNLOAD_SESSION = "UnloadSession",
        SYNC = "Sync",
        PAUSED = "Paused",
        RUNNING = "Running",
        SAVE = "Save",
        DISCONNECT = "Disconnect",
        GAME_MASTER_PAUSE = "GameMasterPause",
        BUILD_STORY = "BuildStory",
        RELOAD_STORY = "ReloadStory",
        INSTALLATION = "Installation"
    },
    CLIENT_STATES = {
        UNKNOWN = "Unknown",
        INIT = "Init",
        INIT_MENU = "InitMenu",
        INIT_NETWORK = "InitNetwork",
        INIT_CONNECTION = "InitConnection",
        IDLE = "Idle",
        LOAD_MENU = "LoadMenu",
        MENU = "Menu",
        EXIT = "Exit",
        SWAP_LEVEL = "SwapLevel",
        LOAD_LEVEL = "LoadLevel",
        LOAD_MODULE = "LoadModule",
        LOAD_SESSION = "LoadSession",
        LOAD_GM_CAMPAIGN = "LoadGMCampaign",
        UNLOAD_LEVEL = "UnloadLevel",
        UNLOAD_MODULE = "UnloadModule",
        UNLOAD_SESSION = "UnloadSession",
        PAUSED = "Paused",
        PREPARE_RUNNING = "PrepareRunning",
        RUNNING = "Running",
        DISCONNECT = "Disconnect",
        JOIN = "Join",
        SAVE = "Save",
        START_LOADING = "StartLoading",
        STOP_LOADING = "StopLoading",
        START_SERVER = "StartServer",
        MOVIE = "Movie",
        INSTALLATION = "Installation",
        GAME_MASTER_PAUSE = "GameMasterPause",
        MOD_RECEIVING = "ModReceiving",
        LOBBY = "Lobby",
        BUILD_STORY = "BuildStory",
        LOAD_LOCA = "LoadLoca"
    }
}
Epip.InitializeLibrary("GameState", GameState)

